"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-5e2-5j0cmh6sxj!su2+glv&$eg3f!b%xy!is5p14=8ub6vlqjs")

DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'core.apps.CoreConfig',
     'users',
     'accounts',
     "documents",
     "vehicles",
     "registrations",
     "ocr",
     "search",
     'staffs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": "db",
        "PORT": "5432",
    }
}

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/minute",
        "user": "200/minute",
        "otp": "5/hour",
        "login": "20/hour",
        "upload": "30/hour",
        "search": "60/minute",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "VEMS API",
    "DESCRIPTION": (
        "Vehicle Entry Management System — AKGEC Campus Security\n\n"
        "## Authentication\n"
        "Most endpoints require a JWT access token (expires in 15 min).\n"
        "1. Register → `POST /api/auth/register/`\n"
        "2. Verify OTP → `POST /api/auth/verify-otp/`\n"
        "3. Set password → `POST /api/auth/set-password/`\n"
        "4. Login → `POST /api/auth/login/` — returns `access_token` and `refresh_token`\n"
        "5. Click **Authorize** above and enter: `Bearer <access_token>`\n"
        "6. Refresh → `POST /api/auth/refresh/` — exchange refresh token for new access token\n\n"
        "## Forgot Password\n"
        "1. `POST /api/auth/forgot-password/` — sends OTP to registered email\n"
        "2. `POST /api/auth/verify-otp/` — verify OTP\n"
        "3. `POST /api/auth/forgot-password/reset/` — set new password\n\n"
        "## Roles\n"
        "- **USER** — Students registering vehicles\n"
        "- **STAFF** — Security guards. Use `GET /api/search/vehicle/staff/` for full student details\n"
        "- **ADMIN** — Admin dashboard only (blocked from `/api/auth/me/`). Promote via Django admin panel\n\n"
        "## Public Endpoints (no auth required)\n"
        "- `GET /api/search/vehicle/?vehicle_number=UP03MF4477` — gate verification lookup\n\n"
        "## Rate Limits\n"
        "- OTP send: 5/hour per IP\n"
        "- Login: 20/hour per IP\n"
        "- Document upload: 30/hour per user\n"
        "- Public search: 60/minute per IP\n\n"
        "## File Upload Rules\n"
        "Documents must be JPG, PNG, WEBP, or PDF. Maximum 5MB."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    "TAGS": [
        {"name": "Auth", "description": "Registration, login, and token management"},
        {"name": "Profile", "description": "User profile management"},
        {"name": "Vehicles", "description": "Vehicle CRUD"},
        {"name": "Documents", "description": "Document upload and management"},
        {"name": "OCR", "description": "OCR processing on uploaded documents"},
        {"name": "Registrations", "description": "Vehicle registration submission and status"},
        {"name": "Search", "description": "Public vehicle search — no auth required"},
        {"name": "Admin", "description": "Admin dashboard — requires ADMIN role"},
    ],
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = os.getenv("EMAIL_PORT")

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']

CSRF_TRUSTED_ORIGINS = [
    "http://vems.akgec.ac.in",
    "https://vems.akgec.ac.in",
]

AUTH_USER_MODEL = "accounts.User"

JAZZMIN_SETTINGS = {
    "site_title": "VEMS Admin",
    "site_header": "VEMS",
    "site_brand": "Software Incubator",
    "site_logo": "img/si-logo.svg",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "img/si-logo.svg",
    "welcome_sign": "AKGEC Vehicle Entry Management System",
    "copyright": "Software Development Centre — Software Incubator, AKGEC",
    "search_model": ["accounts.User", "vehicles.Vehicle", "registrations.VehicleRegistration"],
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Swagger API", "url": "/api/docs/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Swagger API", "url": "/api/docs/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.user": "fas fa-user",
        "users.userprofile": "fas fa-id-card",
        "vehicles.vehicle": "fas fa-car",
        "documents.userdocument": "fas fa-file-alt",
        "registrations.vehicleregistration": "fas fa-clipboard-check",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}