# Generated by Django 6.0.5 on 2026-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_vehicleregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='cross_validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
